apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: sample-app
  namespace: platform

spec:
  project: default

  source:
    repoURL: https://github.com/GandhiMohit4/AI-Infrastructure.git
    targetRevision: HEAD
    path: infrastructure-platform/kubernetes/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: application

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true