jobs:
  terraform:
    name: Terraform - ${{ matrix.environment }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment:
          - dev
          - production

    defaults:
      run:
        working-directory: infrastructure-platform/terraform/environment/${{ matrix.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: infrastructure-platform/terraform

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan